# Generated by Django 2.2.12 on 2026-05-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='course.Course'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainee'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
