# Generated by Django 2.2.12 on 2026-05-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_auto_20260514_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
